# Site settings
title:          CS 저장소
description:    "CS 기록"
baseurl:        ""
url:            "https://sksk713.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         sksk713
  url:          https://sksk713.github.io
  email:        sskk713@ajou.ac.kr

# Build settings
markdown:       kramdown
include:
  - _pages


footer-links:
  email: sskk713@ajou.ac.kr
  # facebook: 
  github: github.com/sksk713
  instagram: s713k
#  linkedin:
#  pinterest:
  rss: # just type anything here for a working RSS icon


# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale